AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  Region:
    Type: String
    Description: The AWS region where the Cognito User Pool is located.
  CognitoId:
    Type: String
    Description: The ID of the Cognito User Pool.
  BackupBucket:
    Type: String
    Description: The name of the S3 bucket where backups will be stored.

Resources:
  CognitoBackupFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.12
      CodeUri: .
      MemorySize: 128
      Timeout: 300
      Environment:
        Variables:
          REGION: !Ref Region
          COGNITO_ID: !Ref CognitoId
          BACKUP_BUCKET: !Ref BackupBucket
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
        - AmazonCognitoPowerUser

  CognitoBackupSchedule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: "Schedule to run Cognito backup twice a day"
      ScheduleExpression: "rate(12 hours)"
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt CognitoBackupFunction.Arn
          Id: "CognitoBackupFunctionTarget"

  PermissionForEventsToInvokeLambda:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !Ref CognitoBackupFunction
      Action: 'lambda:InvokeFunction'
      Principal: 'events.amazonaws.com'
      SourceArn: !GetAtt CognitoBackupSchedule.Arn
